# Infrastructure pipeline that provisions a static web app, a function app, storage account, app service plan and a CosmosDB

trigger:
  - none
pr:
  - none

variables:
  - group: Deployment Variables

pool: Azure Pipelines

stages:
  - stage: ProvisionInfrastructure
    jobs:
    - job: ProvisionInfrastructure
      displayName: Provisioning Infrastructure
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '$(azureResourceManagerConnection)'
          subscriptionId: '$(subscriptionId)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroupName)'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: './azuredeploy.json'
          csmParametersFile: './azuredeploy.parameters.json'
          deploymentMode: 'Incremental'
          deploymentName: 'ProvisionInfrastructure'
          overrideParameters:
            -webAppName "$(webAppName)"
            -appServicePlanName "$(appServicePlanName)"
            -storageAccountName "$(storageAccountName)"
            -functionAppName "$(functionAppName)"
            -location "$(location)"
            -subscriptionId "$(subscriptionId)"
            -resourceGroupName "$(resourceGroupName)"
            -cosmosAccountName "$(cosmosAccountName)"
            -databaseName "$(databaseName)"
            -containerName "$(containerName)"