# A minimal pipeline that provisions a static web app


trigger:
- none

variables:
  - group: Deployment Variables

pool: Default

stages:
- stage: ProvisionStaticWebApp
  jobs:
  - job: ProvisionStaticWebApp
    displayName: Provision Static Web App for Front-end
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureResourceManagerConnection)'
        subscriptionId: '$(subcriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: './azuredeploy.json'
        csmParametersFile: './azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'ProvisionStaticWebApp'
        overrideParameters:
          -webAppName "$(webAppName)"
          -appServicePlanName "$(appServicePlanName)"
          -storageAccountName "$(storageAccountName)"
          -functionAppName "$(functionAppName)"
          -location "$(location)"
          -subcriptionId "$(subcriptionId)"
          -resourceGroupName "$(resourceGroupName)"