# A minimal pipeline that provisions a static web app


trigger:
- none

pool: Default

stages:
- stage: ProvisionStaticWebApp
  jobs:
  - job: ProvisionStaticWebApp
    displayName: Provision Static Web App for Front-end
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureResourceManagerConnection)'
        subscriptionId: '$(subcriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'AzureBlogify'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: './azuredeploy.json'
        csmParametersFile: './azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'ProvisionStaticWebApp'