# Pipeline to deploy a static web app that has a manage Azure Function

trigger:
  - main
pr:
  - none

variables:
  - group: Deployment Variables

pool: Azure Pipelines

stages:
  - stage: DeployStaticWebApp
    jobs:
      - job: DeployStaticWebApp
        displayName: Deploy Static Web App
        steps:
          - task: AzureStaticWebApp@0
            inputs:
              app_location: "$(webAppName)"
              output_location: "dist"
              api_location: "$(webAppName)/api"
              api_build_command: "--configuration Release --output $(Build.ArtifactStagingDirectory) --self-contained false"
              azure_static_web_apps_api_token: $(deploymentToken)
